[package]
name = "thangail"
version = "0.1.1"
edition = "2021"

[dependencies]
reqwest = { version = "0.11",  features = ["rustls-tls"], default-features = false }
rocket = "0.5.0"
rocket_async_compression = "0.5"

[profile.release]
strip = true
